import { StyleSheet } from "react-native";
import { Font } from "../Font";
import { Colors } from "../Colors";

export default StyleSheet.create({
	body: {
		width: "95%",
	},
	bodyContainer: {
		alignSelf: "center",
		borderRadius: 15,
		width: "95%",
		gap: 20,
	},
	programLabel: {
		height: "100%",
		borderRadius: 10,
		textAlign: "center",
		fontFamily: Font.global,
		fontWeight: "bold",
		fontSize: 16,
		borderWidth: 1,
		color: Colors.text_primary,
		borderColor: Colors.border_color,
		backgroundColor: Colors.card_bg,
	},
	programHeader: {
		width: "100%",
		height: 50,
	},
	programFooter: {
		width: "100%",
		height: 50,
		alignItems: "center",
	},
	session: {},
	sessionContainer: {
		width: "100%",
		backgroundColor: Colors.card_bg,
		borderWidth: 1,
		borderColor: Colors.border_color,
		alignSelf: "center",
		borderRadius: 10,
		justifyContent: "space-evenly",
		gap: 10,
	},
	sessionHeader: {
		paddingTop: 10,
		width: "90%",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		alignContent: "center",
		alignSelf: "center",
	},
	sessionLabel: {
		width: "100%",
		color: Colors.text_primary,
		textAlign: "center",
		fontFamily: Font.global,
		fontSize: 16,
		fontWeight: "bold",
	},
	sessionFooter: {
		width: "90%",
		justifyContent: "center",
		alignSelf: "center",
		marginBottom: 10,
		height: 50,
	},
	sessionRemove: {},
	list: {
		width: "100%",
		flexGrow: 0,
	},
	exercisesContainer: { gap: 10 },
	exerciseContainerAnimatedView: {
		width: "90%",
		alignSelf: "center",
		paddingBottom: 10,
		borderBottomWidth: 1,
		borderColor: Colors.border_color,
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 10,
	},
	exerciseContainer: {
		flexShrink: 1,
	},
	delimiter: {
		marginHorizontal: 5,
		borderLeftWidth: 0.5,
		height: "60%",
	},
	exerciseTextInputContainer: {
		width: "100%",
		flexDirection: "row",
		gap: 20,
	},
	exerciseMainLabel: {
		width: "100%",
	},
	exerciseNoteLabel: {
		width: "100%",
	},
	exerciseLabel: {
		width: 110,
		height: 40,
		paddingHorizontal: 10,
		borderWidth: 1,
		borderRadius: 5,
		borderColor: Colors.border_color,
		fontFamily: Font.global,
		fontSize: 14,
		color: Colors.text_primary,
	},
	exercisePicker: {
		paddingHorizontal: 10,
		backgroundColor: Colors.card_bg,
		borderColor: Colors.border_color,
		borderRadius: 5,
		height: 40,
		color: Colors.text_primary,
	},
	exerciseRemove: {
		justifyContent: "center",
	},
	metricView: {
		height: "100%",
		width: "90%",
		maxWidth: 700,
		alignSelf: "center",
		flexDirection: "row",
		justifyContent: "center",
		borderBottomLeftRadius: 10,
		borderBottomRightRadius: 10,
	},
	metricListContainer: {
		height: "100%",
		width: "100%",
	},
	metricList: {},
	metric: {
		marginVertical: 5,
		marginLeft: 10,
		paddingHorizontal: 5,
		flexDirection: "row",
		height: "100%",
		maxHeight: 30,
		borderRadius: 10,
		justifyContent: "center",
		alignItems: "center",
	},
	metricInput: {
		textAlign: "center",
		width: "100%",
		maxWidth: 50,
	},
	metricFooter: {
		height: "100%",
		width: 80,
	},
	addPressable: {
		height: 40,
		width: "100%",
		flexDirection: "row",
		borderRadius: 10,
		justifyContent: "center",
		alignItems: "center",
		gap: 10,
		backgroundColor: Colors.color_primary_base,
	},
	addRemoveLabel: {
		color: Colors.text_primary,
		height: "100%",
		alignContent: "center",
		fontFamily: Font.global,
		fontSize: 16,
	},
});
