import { StyleSheet } from "react-native";
import { Font } from "../Font";
import { Colors } from "../Colors";

export default StyleSheet.create({
	body: {
		flex: 1,
		backgroundColor: Colors.bg_gradient_from,
		justifyContent: "center",
		alignItems: "center",
	},
	titleLabel: {
		textAlign: "center",
		fontFamily: Font.global,
		color: Colors.text_primary,
		fontWeight: "bold",
		fontSize: 20,
	},
	mainLabel: {
		fontFamily: Font.global,
		color: Colors.text_primary,
		fontSize: 16,
	},
	listContainer: {
		alignSelf: "center",
		width: "95%",
		maxWidth: 820,
		backgroundColor: Colors.dim_gray,
		borderRadius: 10,
	},
	list: {
		height: "70%",
		width: "100%",
		flexGrow: 0,
	},
	pressable: {
		flexDirection: "row",
		backgroundColor: Colors.french_gray,
		width: "95%",
		marginTop: 10,
		maxWidth: 800,
		height: 50,
		borderRadius: 5,
		paddingLeft: 10,
		alignSelf: "center",
		alignItems: "center",
		justifyContent: "space-evenly",
		shadowOffset: { height: 2, width: 2 },
		shadowRadius: 5,
		elevation: 5,
	},
	delimiter: {
		borderLeftWidth: 0.5,
		height: "60%",
	},
	pressableMainLabel: {
		color: Colors.text_primary,
		fontFamily: Font.global,
		fontWeight: "bold",
		fontSize: 14,
	},
	header: {
		paddingVertical: 5,
		position: "fixed",
		left: 0,
		top: 0,
		zIndex: 10,
		paddingHorizontal: 20,
		flexDirection: "row",
		height: "100%",
		maxHeight: 50,
		width: "100%",
		justifyContent: "space-between",
	},
	headerPressable: {
		backgroundColor: Colors.button_color,
		height: "50%",
		aspectRatio: 1,
		borderRadius: 50,
		marginHorizontal: 10,
		justifyContent: "center",
		alignItems: "center",
	},
	headerPressableLabel: {
		textAlign: "center",
		fontFamily: Font.global,
		fontSize: 14,
		fontWeight: "bold",
	},
});
